# Editar host si PostgreSQL está en otra computadora.
# Este nombre es un alias de libpq; no es el nombre mostrado en pgAdmin.
[enut2024]
host=localhost
port=5432
dbname=ENUT2024
connect_timeout=10
application_name=curso_enut2024
